development:
  backend:
    ip: 'localhost'
    port: 5000
  frontend:
    ip: 'localhost'
    port: 4200
  database:
    ip: ''
    port: ''
    name: ''
    username: ''
    password: ''
  authorization:
    jwt-key: 'secret'
    session: '1d'
  logging:
    timestamp-format: 'YYYY-MM-DD HH:mm:ss'
    format: '${info.label}|${info.timestamp}|${info.level}|${info.message}'
    warning-folder: 'logging/warning.log'
    error-folder: 'logging/error.log'
    level: 'debug'
  email:
    service: ''
    user: ''
    password: ''
  google-oauth:
    client-id: ''
  github-oauth:
    client-id: ''
    client-secret: ''

production:
  backend:
    ip: 'localhost'
    port: 5000
  frontend:
    ip: 'localhost'
    port: 4200
  database:
    ip: ''
    port: ''
    name: ''
    username: ''
    password: ''
  authorization:
    jwt-key: 'secret'
    session: '1d'
  logging:
    timestamp-format: 'YYYY-MM-DD HH:mm:ss'
    format: '${info.label}|${info.timestamp}|${info.level}|${info.message}'
    warning-folder: 'logging/warning.log'
    error-folder: 'logging/error.log'
    level: 'debug'
  email:
    service: ''
    user: ''
    password: ''
  google-oauth:
    client-id: ''
  github-oauth:
    client-secret: ''
